2023-01-15,19:27:11 [INFO] (app.py:app:244): Parsing config file /usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/app/../common/default.conf
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter port set to "9004" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter server_version set to "2.5.0" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter evaluate_enabled set to "True" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter evaluate_timeout set to "30" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter upload_dir set to "/usr/local/lib/python3.9/dist-packages/tabpy/tmp/query_objects" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter transfer_protocol set to "http" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:212): Parameter certificate_file is not set
2023-01-15,19:27:11 [DEBUG] (app.py:app:212): Parameter key_file is not set
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter state_file_path set to "/usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter static_path set to "/usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/static" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:212): Parameter TABPY_PWD_FILE is not set
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter log_request_context set to "false" from default value
2023-01-15,19:27:11 [DEBUG] (app.py:app:205): Parameter max_request_size_in_mb set to "100" from default value
2023-01-15,19:27:18 [INFO] (app.py:app:244): Parsing config file /usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/app/../common/default.conf
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter port set to "9004" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter server_version set to "2.5.0" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter evaluate_enabled set to "True" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter evaluate_timeout set to "30" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter upload_dir set to "/usr/local/lib/python3.9/dist-packages/tabpy/tmp/query_objects" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter transfer_protocol set to "http" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:212): Parameter certificate_file is not set
2023-01-15,19:27:18 [DEBUG] (app.py:app:212): Parameter key_file is not set
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter state_file_path set to "/usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter static_path set to "/usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/static" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:212): Parameter TABPY_PWD_FILE is not set
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter log_request_context set to "false" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:205): Parameter max_request_size_in_mb set to "100" from default value
2023-01-15,19:27:18 [DEBUG] (app.py:app:430): File /usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/state.ini not found, creating from template /usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/state.ini.template...
2023-01-15,19:27:18 [INFO] (app.py:app:436): Loading state from state file /usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/state.ini
2023-01-15,19:27:18 [DEBUG] (app.py:app:313): Static pages folder set to "/usr/local/lib/python3.9/dist-packages/tabpy/tabpy_server/static"
2023-01-15,19:27:18 [INFO] (app.py:app:332): Password file is not specified: Authentication is not enabled
2023-01-15,19:27:18 [INFO] (app.py:app:347): Call context logging is disabled
2023-01-15,19:27:18 [INFO] (app.py:app:125): Initializing TabPy...
2023-01-15,19:27:18 [DEBUG] (selector_events.py:selector_events:59): Using selector: EpollSelector
2023-01-15,19:27:18 [INFO] (callbacks.py:callbacks:43): Initializing TabPy Server...
2023-01-15,19:27:18 [DEBUG] (state.py:state:613): Loading option 'None' from section [Query Objects Service Versions]...
2023-01-15,19:27:18 [DEBUG] (state.py:state:635): Returning value '[]'
2023-01-15,19:27:18 [DEBUG] (state.py:state:148): Collected endpoints: {}
2023-01-15,19:27:18 [INFO] (app.py:app:129): Done initializing TabPy.
2023-01-15,19:27:18 [INFO] (app.py:app:83): Setting max request size to 104857600 bytes
2023-01-15,19:27:18 [INFO] (callbacks.py:callbacks:64): Initializing models...
2023-01-15,19:27:18 [DEBUG] (state.py:state:613): Loading option 'None' from section [Query Objects Service Versions]...
2023-01-15,19:27:18 [DEBUG] (state.py:state:635): Returning value '[]'
2023-01-15,19:27:18 [DEBUG] (state.py:state:148): Collected endpoints: {}
2023-01-15,19:27:18 [INFO] (app.py:app:106): Web service listening on port 9004
2023-01-15,19:27:26 [INFO] (web.py:web:2271): 200 GET / (127.0.0.1) 28.50ms
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Checking if need to handle authentication
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Handling authentication
2023-01-15,19:27:26 [INFO] (base_handler.py:base_handler:115): Authentication is not a required feature for API "v1"
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Checking request headers for authentication data
2023-01-15,19:27:26 [INFO] (base_handler.py:base_handler:115): Authorization header not found
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): authentication not required, username and password are none
2023-01-15,19:27:26 [DEBUG] (state.py:state:511): Collecting Access-Control-Allow-Origin from state file ...
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Origin' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Headers' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Methods' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Description' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Creation Time' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value '0'
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Name' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value 'TabPy Server'
2023-01-15,19:27:26 [INFO] (web.py:web:2271): 200 GET /info (127.0.0.1) 18.65ms
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Checking if need to handle authentication
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Handling authentication
2023-01-15,19:27:26 [INFO] (base_handler.py:base_handler:115): Authentication is not a required feature for API "v1"
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): Checking request headers for authentication data
2023-01-15,19:27:26 [INFO] (base_handler.py:base_handler:115): Authorization header not found
2023-01-15,19:27:26 [DEBUG] (base_handler.py:base_handler:115): authentication not required, username and password are none
2023-01-15,19:27:26 [INFO] (web.py:web:2271): 200 GET /tableau.png (127.0.0.1) 3.98ms
2023-01-15,19:27:26 [DEBUG] (state.py:state:511): Collecting Access-Control-Allow-Origin from state file ...
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Origin' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Headers' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'Access-Control-Allow-Methods' from section [Service Info]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value ''
2023-01-15,19:27:26 [DEBUG] (state.py:state:613): Loading option 'None' from section [Query Objects Service Versions]...
2023-01-15,19:27:26 [DEBUG] (state.py:state:635): Returning value '[]'
2023-01-15,19:27:26 [DEBUG] (state.py:state:148): Collected endpoints: {}
2023-01-15,19:27:26 [INFO] (web.py:web:2271): 200 GET /endpoints (127.0.0.1) 6.08ms
2023-01-15,19:27:26 [WARNING] (web.py:web:2271): 404 GET /favicon.ico (127.0.0.1) 1.40ms
